language: python

python:
    - "3.7"

branches:
  only:
    - master

services:
  - docker

env:
  - ENV=TEST

install:
  - pip install poetry
  - poetry install

script: 
  - poetry run black . --check
  - poetry run coverage run -m pytest -v
  - poetry run coverage report

after_success:
  - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
  - docker pull $DOCKERHUB_USERNAME/akingbee:prod
  - docker tag $DOCKERHUB_USERNAME/akingbee:prod $DOCKERHUB_USERNAME/akingbee:previous
  - docker push $DOCKERHUB_USERNAME/akingbee:previous
  - docker build -t $DOCKERHUB_USERNAME/akingbee:prod .
  - docker push $DOCKERHUB_USERNAME/akingbee:prod
