language: python

python:
    - "3.7"

services:
  - docker

stages:
  - test
  - publish

jobs:
  include:

    - stage: test
      script: |
        pip install poetry
        poetry install
        poetry run black . --check
        poetry run coverage run -m pytest -v
        poetry run coverage report

    - stage: publish
      script: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
        docker build -t $DOCKERHUB_USERNAME/akingbee:$TRAVIS_TAG .
        docker push $DOCKERHUB_USERNAME/akingbee:$TRAVIS_TAG
      if: tag IS present
