version: "3.7"

services:
  cerbes:
    image: yomain/cerbes:latest
    container_name: cerbes
    environment:
      - SERVICE_NAME=cerbes
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DATABASE=akb_dev
      - AKB_RBMQ_USER=akingbee
      - AKB_RBMQ_PASSWORD=password
      - AKB_RBMQ_HOST=rbmq
      - AKB_RBMQ_PORT=5672
      - AKB_RBMQ_VHOST=/
    ports:
      - 9001:9001
    networks:
      - akb

  aristaeus-api:
    image: yomain/aristaeus:latest
    container_name: aristeaus-api
    environment:
      - SERVICE_NAME=aristaeus-api
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DATABASE=akb_dev
      - CERBES_ENDPOINT=cerbes
    ports:
      - 9002:9002
    networks:
      - akb

  aristaeus-listener:
    image: yomain/aristaeus:latest
    container_name: aristeaus-listener
    environment:
      - SERVICE_NAME=aristaeus-listener
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DATABASE=akb_dev
      - AKB_RBMQ_USER=akingbee
      - AKB_RBMQ_PASSWORD=password
      - AKB_RBMQ_HOST=rbmq
      - AKB_RBMQ_PORT=5672
      - AKB_RBMQ_VHOST=/
      - CERBES_ENDPOINT=cerbes
    command: python ./aristaeus/listener.py
    networks:
      - akb

  migration:
    image: yomain/gaea:latest
    container_name: migration
    environment:
      - SERVICE_NAME=migration
      - AKB_DATABASE_HOST=db
      - AKB_DATABASE_USER=akingbee
      - AKB_DATABASE_PASSWORD=123
      - AKB_DATABASE_DATABASE=akb_dev
    depends_on:
      - db
    networks:
      - akb



  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   restart: "always"
  #   command: ["/etc/nginx/start.sh"]
  #   environment:
  #     TZ: Europe/Paris
  #     NGINX_AUTH_USERNAME: ${NGINX_AUTH_USERNAME}
  #     NGINX_AUTH_PWD: ${NGINX_AUTH_PWD}
  #   volumes:
  #     - /etc/letsencrypt:/certs
  #     - ./infra/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./infra/conf/nginx/start.sh:/etc/nginx/start.sh
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - akingbee
  #   networks:
  #     - akb

  db:
    image: postgres:10-alpine
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: akb_dev
      POSTGRES_USER: akingbee
      POSTGRES_PASSWORD: "123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - akb

  rbmq:
    image: rabbitmq:management-alpine
    container_name: rbmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: akingbee
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - akb

networks:
    akb:

