version: "3.7"

services:
  prod:
    image: tianon/true
    depends_on: [akingbee, redis, messaging_bee, nginx]
    networks:
      - akingbee_nw


  dev:
    image: tianon/true
    depends_on: [prod, elastic, kibana]
    networks:
      - akingbee_nw


  akingbee:
    image: yomain/akingbee:prod
    container_name: akingbee
    expose:
      - 8080
    volumes:
      - .env:/app/.env
      - ./log:/app/log
    environment:
      - REDIS_HOST=redis
      - SERVICE_NAME=webapp
      - IDENTIFIER=AKB
    command: uwsgi --ini ./uwsgi.ini
    restart: "always"
    depends_on:
      - redis
      - messaging_bee
    networks:
      - akingbee_nw

  messaging_bee:
    image: yomain/akingbee:prod
    user: 1000:1000
    container_name: messaging_bee
    volumes:
      - .env:/app/.env
      - ./log:/app/log
    environment:
      - REDIS_HOST=redis
      - SERVICE_NAME=messaging
      - IDENTIFIER=AKB
    command: python listener.py
    restart: "always"
    depends_on:
      - redis
    networks:
      - akingbee_nw

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: "always"
    command: ["/etc/nginx/start.sh"]
    environment:
      TZ: Europe/Paris
      NGINX_AUTH_USERNAME: ${NGINX_AUTH_USERNAME}
      NGINX_AUTH_PWD: ${NGINX_AUTH_PWD}
    volumes:
      - /etc/letsencrypt:/certs
      - ./infra/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/conf/nginx/start.sh:/etc/nginx/start.sh
    ports:
      - 80:80
      - 443:443
    depends_on:
      - akingbee
    networks:
      - akingbee_nw

  redis:
    image: redis:rc-alpine
    container_name: redis
    expose:
      - 6379
    restart: always
    networks:
      - akingbee_nw

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elastic
    restart: always
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./infra/conf/elk/cache/elastic:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - akingbee_nw

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    volumes:
      - ./infra/conf/elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - akingbee_nw

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.6.1
    restart: always
    environment:
      - setup.kibana.host=kibana:5601
    volumes:
      - ./infra/conf/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./log:/var/log:ro
    networks:
      - akingbee_nw


networks:
    akingbee_nw:

