version: "3"

services:
    akingbee:
        image: yomain/akingbee:prod
        container_name: akingbee
        expose:
            - 8080
        volumes:
                - .env:/app/.env
        command: uwsgi --ini ./conf/uwsgi.ini
        restart: "always"
        networks:
            - akingbee_nw
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: "always"
        environment:
            TZ: Europe/Paris
        volumes:
            - /etc/letsencrypt:/certs
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
            - 443:443
        depends_on:
            - akingbee
        networks:
            - akingbee_nw

networks:
    akingbee_nw:

