clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: akingbee
    entry_parser: raw

    pipeline_stages:
      - json:
          expressions:
            job: name
            user_id: user_id
            message: message
            duration: duration
            levelname: levelname
            timestamp: timestamp
            status_code: status_code
            request_method: request_method
            request_ip_address: request_ip_address
            request_form: request_form
            pathname: pathname
            request_path: request_path
            lineno: lineno
            funcName: funcName
            request_user_agent: request_user_agent
      - template:
          source: log_message
          template: '{{ .levelname }} - {{ .user_id }} - {{ .request_ip_address }} - {{ .request_path }} - {{ .message }}'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          job:
          user_id:
          message:
          duration:
          levelname:
          status_code:
          request_method:
          pathname:
          lineno:
          funcName:
          request_ip_address:
          request_form:
          request_user_agent:
      - output:
          source: log_message

    static_configs:
      - targets: [localhost]
        labels:
          __path__: /var/log/*.log

