DEFAULT:
  LOG_LEVEL: 20
  SERVICE_NAME: "gaea"


DEVELOPMENT:
  LOGS_FOLDER_NAME: "log"

  DATABASE_PORT: 5432
  DATABASE_HOST: "127.0.0.1"
  DATABASE_USER: "akingbee"
  DATABASE_PASSWORD: ""
  DATABASE_DATABASE: "akb_dev"

