filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    encoding: utf-8
    fields_under_root: true
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["elastic:9200"]

processors:
- add_cloud_metadata: ~
