[tool.poetry]
name = "aristaeus"
version = "0.1.0"
description = ""
authors = ["rarnal <arnal.romain@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2"
aiohttp = "^3"
gaea = "^0"

[tool.poetry.dev-dependencies]
pylint = "*"
pytest = "*"
black = "*"
mock = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
