apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  tls:
  - hosts:
    - yo-main.com
    - log.yo-main.com
    secretName: yo-main.com-tls
  rules:
  - host: log.yo-main.com
    http:
      paths:
        - backend:
            serviceName: kibana
            servicePort: 5601
  - host: yo-main.com
    http:
      paths:
        - backend:
            serviceName: akingbee
            servicePort: 8080

