apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "akb-entrypoint"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hostingroa@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: akingbee.com
  namespace: default
spec:
  secretName: akingbee.com-tls
  issuerRef:
    name: letsencrypt
  commonName: akingbee.com
  dnsNames:
  - akingbee.com
  - www.akingbee.com
  - grafana.akingbee.com
