apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hostingroa@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: yo-main.com
  namespace: default
spec:
  secretName: yo-main.com-tls
  issuerRef:
    name: letsencrypt
  commonName: yo-main.com
  dnsNames:
  - yo-main.com
  - log.yo-main.com

