DEFAULT:
  SERVICE_NAME: "cerbes"
  LOG_LEVEL: 20

DEVELOPMENT:
  LOGS_FOLDER_NAME: "log"
  APP_SECRET: "coucou"

  DATABASE_PORT: 5432
  DATABASE_HOST: "127.0.0.1"
  DATABASE_USER: "akingbee"
  DATABASE_PASSWORD: "password"
  DATABASE_DATABASE: "akb_dev"

  RBMQ_PORT: 5672
  RBMQ_HOST: "127.0.0.1"
  RBMQ_USER: "akingbee"
  RBMQ_PASSWORD: "password"
  RBMQ_VHOST: "/"
