DEFAULT:
  SERVICE_NAME: "cerbes"

DEVELOPMENT:
  LOGS_FOLDER_NAME: "log"
  LOG_LEVEL: 0

  DATABASE_PORT: 3306
  DATABASE_HOST: "127.0.0.1"
  DATABASE_USER: "akingbee"
  DATABASE_PASSWORD: "password"
  DATABASE_DATABASE: "akb_dev"
