[tool.poetry]
name = "cerbes"
version = "0.1.0"
description = ""
authors = ["rarnal <arnal.romain@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyjwt = "^1.7.1"
uvicorn = "^0.11.8"
pydantic = "^1.6.1"
fastapi = "^0.61.0"
gaea = "^0.1.15"

[tool.poetry.dev-dependencies]
pylint = "^2.5.3"
ipython = "^7.17.0"
pytest = "^6.0.1"
requests = "^2.24.0"
coverage = "^5.2.1"
black = "^20.8b1"
mock = "^4.0.2"

[tool.coverage.run]
omit = [".venv/*", "tests/*", "*/gaea/*"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
