apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
  # acme:
  #   # server: https://acme-staging-v02.api.letsencrypt.org/directory
  #   server: https://acme-v02.api.letsencrypt.org/directory
  #   email: hostingroa@gmail.com
  #   privateKeySecretRef:
  #     name: letsencrypt
  #   solvers:
  #   - dns01:
  #       digitalocean:
  #         tokenSecretRef:
  #           name: digitalocean-dns
  #           key: access-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: akingbee-tls
  namespace: default
spec:
  secretName: akingbee-tls
  issuerRef:
    name: selfsigned-issuer
  commonName: akingbee.test
  dnsNames:
  - akingbee.test
  - '*.akingbee.test'
