configMapGenerator:
- name: env-vars-config
  env: production.env

secretGenerator:
- name: env-secrets-config
  env: production.secrets

bases:
- ../../applications
- ../../core
- ../../jobs

resources:
- letsencrypt.yaml
- secrets.yaml

images:
- name: yomain/aristaeus
  newTag: 1.7.13
- name: yomain/cerbes
  newTag: 1.8.0
- name: yomain/hermes
  newTag: 1.1.1
- name: yomain/poseidon
  newTag: 1.6.3

vars:
- name: MAIN_HOSTED_ZONE
  objref:
    kind: ConfigMap
    name: env-vars-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DNS