configMapGenerator:
- name: env-vars-config
  env: production.env
  namespace: default
  options:
    disableNameSuffixHash: false

secretGenerator:
- name: env-secrets-config
  env: production.secrets
  options:
    annotations:
      kustomize.config.k8s.io/behavior: replace
    disableNameSuffixHash: false
  namespace: default

bases:
- ../../applications
- ../../core
- ../../jobs

resources:
- letsencrypt.yaml
- secrets.yaml

images:
- name: yomain/aristaeus
  newTag: 1.7.15
- name: yomain/cerbes
  newTag: 1.8.2
- name: yomain/hermes
  newTag: 1.1.3
- name: yomain/poseidon
  newTag: 1.6.5

vars:
- name: MAIN_HOSTED_ZONE
  objref:
    kind: ConfigMap
    name: env-vars-config
    apiVersion: v1
  fieldref:
    fieldpath: data.DNS
